

Parte 1 



In [1]:
planetas = ["Mercurio", "Venus", "Tierra", "Marte", "Júpiter", "Saturno", "Urano", "Neptuno"]

In [2]:
print (planetas)

['Mercurio', 'Venus', 'Tierra', 'Marte', 'Júpiter', 'Saturno', 'Urano', 'Neptuno']


In [3]:
len(planetas)

8

In [7]:
print(planetas[1:2])

['Venus']




Parte 2



In [8]:
F = 30.3

In [13]:
C = [5/9*F-32]
print(C)

[-15.166666666666664]




Parte 3 



In [3]:
import numpy as np

In [10]:
numeros = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

In [11]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (row major) unless 'F' is
    specified, in which case it will be in Fortran order (c

In [30]:
np.reshape?

Signature: np.reshape(a, newshape, order='C')
Docstring:
Gives a new shape to an array without changing its data.

Parameters
----------
a : array_like
    Array to be reshaped.
newshape : int or tuple of ints
    The new shape should be compatible with the original shape. If
    an integer, then the result will be a 1-D array of that length.
    One shape dimension can be -1. In this case, the value is
    inferred from the length of the array and remaining dimensions.
order : {'C', 'F', 'A'}, optional
    Read the elements of `a` using this index order, and place the
    elements into the reshaped array using this index order.  'C'
    means to read / write the elements using C-like index order,
    with the last axis index changing fastest, back to the first
    axis index changing slowest. 'F' means to read / write the
    elements using Fortran-like index order, with the first index
    changing fastest, and the last index changing slowest. Note that
    the 'C' and 'F' options ta

In [16]:
numeros4x4 = np.reshape(numeros, (4, 4))
print(numeros4x4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


Parte 4 


In [5]:
angulos = [(0, 30, 45, 60, 90)] 

In [7]:
radianes = np.radians(angulos)
print(radianes)

[[0.         0.52359878 0.78539816 1.04719755 1.57079633]]


In [9]:
seno = np.sin (angulos)
print (seno)

[[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]]


In [43]:
coseno = np.cos (angulos)
print (coseno)

[[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]]





Parte 5 


